* Services Mode

This is an Emacs mode to give you a UI for managing init system services.

** Init system support

Only =systemd= and =SysVinit= right now, but it's designed to be extensible.

** Usage

You can open the services list with =M-x services=.

Navigate the list with =n= and =p=. Refresh the list with =g= (it's just a =tabulated-list-mode= buffer).

The following commands are available for each service:

| Key | Command             |
|-----+---------------------|
| RET | Show service status |
| s   | Start service       |
| S   | Stop service        |
| r   | Reload service      |
| R   | Restart service     |

Results of commands are displayed in a =special-mode= buffer, in which the same commands are available for the relevant service. You can dismiss it with =q=.

** Installation

Currently just =(load-file "/path/to/services.el")=.

You could also clone the repo, then run =make= and =M-x package-install-file services-0.0.2= to install the package.

** Configuration

Please see =M-x customize-mode=.

** Extending

If you write a package that assigns

- =services--commands-alist=
- =services--list-fun=
- =services--list-headers-fun=

to your own implementations and set custom variable =services-init-system-submodule= to that package then =M-x services= should just work for your system. You'll need to restart Emacs or manually load your package on first use.
