#+TODO: TODO IN-PROGRESS DONE
* Services Mode

This is an Emacs mode to give you a UI for managing init system services.

** Init system support

Only =systemd= right now, but it's designed to be extensible. SysVinit is next on the list.

** Usage

You can open the services list with =M-x services=.

Navigate the list with =n= and =p=. Refresh the list with =g= (it's just a =tabulated-list-mode= buffer).

The following commands are available for each service:

| Key | Command             |
|-----+---------------------|
| RET | Show service status |
| s   | Start service       |
| S   | Stop service        |
| r   | Reload service      |
| R   | Restart service     |

Results of commands are displayed in a =special-mode= buffer, in which the same commands are available for the relevant service. You can dismiss it with =q=.

** Installation

Currently just =(load-file "/path/to/services.el")=.

** Configuration

Please see =M-x customize-mode=.

** Roadmap                                                         :noexport:
*** IN-PROGRESS SysVinit support
**** DONE Define commands (basic support)
**** TODO Enable injecting shell-command handlers
**** TODO Implement better submodule system
**** TODO Define (and test) submodule contract
*** TODO Package install
*** TODO sc.exe support
*** TODO launchctl support
